# Site settings
author: Christian Polanco
title: Day and Night and everything in between 
header-img: img/home-bg.png
email: chrispolanco@sbcglobal.net
copyright_name: Christian Polanco
description: > # this means to ignore newlines until "baseurl:"
  Short Essay's about taking steps forward 
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  Chrispolanco

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
